#!/bin/sh
git config user.name > /dev/null && git config user.email > /dev/null
RETVAL=$?
if [ $RETVAL -ne 0 ]; then
    echo "Please set your user NAME and EMAIL for this repo"
    echo "Ex."
    echo "    git config --local user.name <NAME>"
    echo "    git config --local user.email <EMAIL>"
    exit 1
fi

if [ "$(git config branch.autosetuprebase)" != "always" ]; then
    echo "Please set autosetuprebase"
    echo "Ex."
    echo "    git config branch.autosetuprebase always"
    exit 1
fi

if [ "$(git config push.default)" != "tracking" ]; then
    echo "Please set up your push default"
    echo "Ex."
    echo "    git config push.default tracking"
    exit 1
fi

exit 0
